### ISSUE TITLE
Need callback on the parser function

### ISSUE THREAD

**Issue by Redsandro** [Poetro/node-xml2js-expat#5]
Wouldn't it make sense to have the (or _a_) callback on `parseString()` itself?

```
var parser = new xml2js.Parser('UTF-8');

parser.parseString(someXml, someCallback);
parser.parseString(otherXml, otherCallback);
```

This has the added benefit of wrapping in promises nicely, and removing the overhead of creating a new `Parser` for every other callback.

**Comment by clodio** [comment]
+1

**Comment by Redsandro** [comment]
@Poetro any updates? Setting up xml2js-expat requires the most code of all parsers, but it's still third place in the rankings.

name | rank | ms
---- | ---- | ---
rapidx2j | 1 | 169 ms
nkit | 2 | 222 ms
**x2je** | **3** | **359 ms**
xml2json | 4 | 386 ms
xml2js | 5 | 808 ms

https://github.com/Redsandro/node-xml2js-olympics#rankings

**Comment by Poetro** [comment]
You'll have to create a new parser for every parsing.
```javascript
function parseString(encoding, callback, value) {
  var parser = new xml2js.Parser(encoding, callback)
  return parser.parseString(value)
}
```

**Comment by Redsandro** [comment]
Doesn't `return parser.parseString(value)` make the function blocking and defeat the purpose of a callback?

**Comment by Poetro** [comment]
parseString is mosyly synchronous anyways, but now there is way to parse the code asynchronously with streaming in the data. The value that parseString returns falsy value if there was any error. The rest of the parsing is done in events emmited by [node-expat](https://github.com/astro/node-expat).
